### ISSUE TITLE
Add mega menu styling to CSS

### ISSUE THREAD

**Issue by bergeson** [fsoe-asu/fultonSchoolsDiviTheme#10]
Please add (and tweak if needed to be WS-compliant, I think the font may be too small) mega-menu styling to the theme:
# top-menu li.mega-menu > ul > li > a:first-child, .fullwidth-menu-nav li.mega-menu > ul > li > a:first-child

.et_header_style_centered #top-menu li.mega-menu > ul {
text-transform:uppercase;
border-bottom:1px solid #FFB310;
font-size:14px; /_difference_/
line-height:normal; /_difference_/
}
# top-menu li.mega-menu ul li, .fullwidth-menu-nav li.mega-menu ul li {

```
font-size:12px;
line-height:normal;
```

}

**Comment by bergeson** [comment]
Steve, I would really like this for the Poly site, which I'd like to make live by Wed, 7/27. Possible?

**Comment by SteveRyan-ASU** [comment]
Hi Kristin,

Added some CSS that achieves the same effect as the above styles do, but in a more persistent way. Added code is this:

```
    #top-menu li.mega-menu > ul > li > a:first-child {
        font-weight:bold;
        border-bottom:1px solid #FFB310;
        font-size:14px;
        line-height:normal;
        text-transform:uppercase;
        margin-bottom:5px;
    }

    #top-menu li.mega-menu > ul > li > ul > li > a {
        border-bottom: none;
        font-weight: normal;
        font-size:13px;
        line-height:normal;
    }
```

And the effect is this:
![2016-08-01_11-19-52](https://cloud.githubusercontent.com/assets/2085753/17304414/5964611c-57da-11e6-8b65-98905922f4e3.png)

**Comment by SteveRyan-ASU** [comment]
A note for the future: Our current style of mega-menus isn't fully supported by the Brand Guide. But, I think it's probably a very valid option for styling these mega menus in a way that achieves a better UX than the recommendation.

**Comment by SteveRyan-ASU** [comment]
Investigation / implementation of this issue lead to the creation of a separate issue with the active and hover states for the main navigation. That issue will be addressed in a different release.

See [Issue 14](https://github.com/fsoe-asu/fultonSchoolsDiviTheme/issues/14) for more details.
