### ISSUE TITLE
Remove underline decoration from filterable portfolio tabs

### ISSUE THREAD

**Issue by bergeson** [fsoe-asu/fultonSchoolsDiviTheme#11]
See: http://move.engineering.asu.edu/poly/advising/meet-your-advisors/
Scroll to bottom for Filterable portfolio and notice that the tabs have dotted underline decoration instead of just having the continuous thin grey line around them (compare to http://poly.engineering.asu.edu/advising/meet-your-advisors/ while they are both still live).

**Comment by SteveRyan-ASU** [comment]
By default, the filterable portfolio module gave you the following look/feel as of FSDT 1.7. Identified fixes are outlined within the image.

![2016-12-28_14-04-26](https://cloud.githubusercontent.com/assets/2085753/21533315/8300a632-cd16-11e6-83e2-da053b8276c9.jpg)

The fix applies styles associated with the ASU Web Standards to the filter bar. (Styles based on the Tab control found [within the UI Kit](https://brandguide.asu.edu/web-standards/enterprise/ui-kit).) I also took away the need for the portfolio items to be styled like links. The result is a cleaner look to each item that still behaves correctly when hovered over.

As a result of the changes, the filterable portfolio now looks like the following out of the box.
![2016-12-28_15-52-25](https://cloud.githubusercontent.com/assets/2085753/21533358/e87377ce-cd16-11e6-9ab1-5cad913ec0c3.png)

**Comment by SteveRyan-ASU** [comment]
Pull Request #24 fixes this request.
