### ISSUE TITLE
Minor enhancements, bug fixes.

### ISSUE THREAD

**Issue by SteveRyan-ASU** [fsoe-asu/fultonSchoolsDiviTheme#16]
Other minor enhancements requested:
- Uncomment line #528 in CSS to address fixed (but not implemented?) overlay fix for sliders.
- Add ASU Header Fixes from GIOS Web Standards Theme. (Changes to menu items.)
- Remove padding-right from all external link icons. Also make sure that images w/external links don't have the icon applied to them.

**Comment by bergeson** [comment]
This is fussy, I know, but I'd like to put an express order on that padding-right elimination on external link icons. If I have to look at one more word-wrapped external link icon floating around by itself on the second line, I'm going to scream.

I think the original issue was that the icon was just about touching the text to which it was attached. It just needed a little bit of left padding, maybe half a character space. THANK YOU :)

**Comment by SteveRyan-ASU** [comment]
Incorporating the fix for the third bullet point here in the work done for #22, along with the general concern for "automatically, except when there are linked images."

**Comment by SteveRyan-ASU** [comment]
Adjusting the margins around the external link icon to `padding: 0 2px 0 6px;` seems to produce a good effect for inline links.
