### ISSUE TITLE
Fulton Schools Menu Issues

### ISSUE THREAD

**Issue by bergeson** [fsoe-asu/fultonSchoolsDiviTheme#21]
1. Degree Programs is spelled wrong (Degre Programes)
2. When loaded into Pantheon, Pantheon changes the links in the menu. A second, complete panthoen link going to the homepage of the dev site is added to each menu item before the real link. For example, 
   https://engineering.asu.edu/factbook/
   becomes
   http://dev-ssebe-fsdt.pantheonsite.io/https://engineering.asu.edu/factbook/

**Comment by SteveRyan-ASU** [comment]
Fixing the spelling in `functions.php:146` solved the spelling error.

**Comment by SteveRyan-ASU** [comment]
Marking this issue as completed to separate the two concerns presented here. The additional requirement about the broken Pantheon links has been recaptured in a different issue. (#23)
