### ISSUE TITLE
Reformat Fulton Sidebar

### ISSUE THREAD

**Issue by bergeson** [fsoe-asu/fultonSchoolsDiviTheme#9]
We have a Fulton Schools Sidebar widget that renders like this:
http://move.engineering.asu.edu/poly/ph-d-in-systems-engineering/

We would like it to look and function more like this if possible:
https://wpcarey.asu.edu/undergraduate-degrees/programs

If that can't be done, we could always create "sidebars" which are actually Divi permanent library items.

**Comment by bergeson** [comment]
Just adding that the current widget is behaving a bit unpredictably in the Poly dev site. I've created two sidebars using the widget which are virtually identical, the Eng MS Sidebar and the HSE PhD Sidebar. Both have the Fulton widget and a text widget inside. In one, the logo displays, in the other it does not:
http://move.engineering.asu.edu/poly/ms-hse/  (works)

http://move.engineering.asu.edu/poly/simulation-modeling-and-applied-cognitive-science/ (doesn't work)

I find this really strange...

**Comment by SteveRyan-ASU** [comment]
Initial fix in 1.7 applied a specific class to address these formatting concerns. In the next release, it'll be fixed globally with nothing further needed.
